from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages to be processed by the agent")
    user_question: str = Field(..., description="The original question asked by the user")
    curated_question: str = Field(..., description="Curated user questions")
    prompt_query_context : str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent based on the curated question and prompt context")
    is_safe: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments : str = Field(..., description="Comments regarding the safety of the generated SQL query")
    sql_query_execution_result: str = Field(..., description="The result of executing the generated SQL query")
    final_answer: str = Field(..., description="The final answer generated by the agent after processing the messages and executing the SQL query")
